version: "3"

services:
  nginx:
    build:
      context: docker/frontend/development/nginx
    ports:
      - "7770:80"
    volumes:
      - ./frontend:/app
  api:
    build:
      context: docker/api/development/nginx
    ports:
      - "7771:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm
  api-php-fpm:
    build:
      context: docker/api/development/php-fpm
    volumes:
      - ./api:/app
