version: "3"

services:
  gateway:
    build:
      context: docker/development/gateway/nginx
    ports:
      - "7770:7770"
      - "7771:7771"
    depends_on:
      - frontend
      - api
  frontend:
    build:
      context: docker/development/frontend/nginx
    volumes:
      - ./frontend:/app
  api:
    build:
      context: docker/development/api/nginx
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm
  api-php-fpm:
    build:
      context: docker/development/api/php-fpm
    volumes:
      - ./api:/app
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
  api-php-cli:
    build:
      context: docker/development/api/php-cli
    volumes:
      - ./api:/app
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
